### ISSUE TITLE
Pause music playing in background

### ISSUE THREAD

**Issue by Mrudula1205** [ShwetKhatri2001/Swetify-Music#10]
I would like to pause music playing in the background when the class is switched to homepage_content from music_container by clicking any of the icons on the navbar.
Please assign me this issue.

**Comment by Mrudula1205** [comment]
@ShwetKhatri2001 please assign me this issue under hacktoberfest

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead and fix that @Mrudula1205. You're assigned.
