### ISSUE TITLE
addition of another artist under popular artist 

### ISSUE THREAD

**Issue by GhoshAditi** [ShwetKhatri2001/Swetify-Music#100]
### What would you like to share?

would like to add sonu nigam and his songs under popular artists

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
Okay, add at least 5 songs of the artist.
Also, if the UI needs some improvement while adding those then take care of that.
