### ISSUE TITLE
Adding the search bar at the nav bar on the right corner

### ISSUE THREAD

**Issue by Souvik34** [ShwetKhatri2001/Swetify-Music#104]
### Description

Addition of the search bar at the nav bar on the right corner so that the user experience is good to search any songs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by ShwetKhatri2001** [comment]
It's a duplicate issue. Have a look at #32 .

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate issue.
