### ISSUE TITLE
Animating Buttons

### ISSUE THREAD

**Issue by Vikranthraosb** [ShwetKhatri2001/Swetify-Music#107]
### What's the style idea?

Button looks dull for the ui. Can add better After css property for better user experience 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
Can you please give some examples, of which buttons you're talking about?

**Comment by Vikranthraosb** [comment]
https://github.com/ShwetKhatri2001/Swetify-Music/assets/102306707/c318962a-a02f-4328-a671-c2f71ef8aa02

Like This ( Will cahnge color theme )

**Comment by ShwetKhatri2001** [comment]
I meant, Which buttons on our website? There is only one I see that can be updated - The `Send` button on the contact page.
You may change that probably. Assigning you for that.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Vikranthraosb ? Please try to complete it in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Let's give a chance to other contributors to work on this. 
This issue is open to contributors.

**Comment by dipayan22** [comment]
hey @ShwetKhatri2001 ,I am Dipayan Majumder , participant in SWOC 24 .Can you assign me this project .
