### ISSUE TITLE
Changing Scroll bar UI

### ISSUE THREAD

**Issue by Vikranthraosb** [ShwetKhatri2001/Swetify-Music#108]
### What's the style idea?

Instead of plane Scrollbar, We can add customised scrollbar for better UI

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
Okay, update that. Make sure you stick with theme colors.

**Comment by Muhammad-Owais-Warsi** [comment]
@ShwetKhatri2001 @Vikranthraosb Hey, is this issue solved or not? Really want to solve this :)
