### ISSUE TITLE
Bug regarding mobile view and disappearing page and contact page

### ISSUE THREAD

**Issue by tushargupta1504** [ShwetKhatri2001/Swetify-Music#112]
### Description

The bug is in mobile phone view there is no option to hide the menu it should be in a toggle switch and the home buttons like home , popular catg this should be in a three dot button in mobile view for the convienence of user and also the page is disappearing many time also i there is a problem with the contact page .

I want to make the changes that wanted a improved version for mobile browsers + modifying the code of pages which are disappearing not working proprly

### Screenshots

<img width="322" alt="image" src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/138330699/4bfc4447-2c39-4023-81fc-b463659ed652">
![WhatsApp Image 2024-01-14 at 21 05 36_8634e845](https://github.com/ShwetKhatri2001/Swetify-Music/assets/138330699/1eac3b5e-0d98-470a-8438-b69f971ae680)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by tushargupta1504** [comment]
Pls accept my PR
and assign this issue to me..

**Comment by ShwetKhatri2001** [comment]
This is a duplicate issue. There is an issue raised integrating this and it's assigned already. You can have a look and work on that next.

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate issue.
