### ISSUE TITLE
[Feature] Add Contributor Section

### ISSUE THREAD

**Issue by rishicds** [ShwetKhatri2001/Swetify-Music#117]
### Description

I'd like to add a section which shows all the contributors of this project

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by ShwetKhatri2001** [comment]
Go ahead. Add it to the About page only.

**Comment by ShwetKhatri2001** [comment]
Completed by PR #124
