### ISSUE TITLE
addition of shreya ghosal to the best of artists section

### ISSUE THREAD

**Issue by GhoshAditi** [ShwetKhatri2001/Swetify-Music#118]
### What would you like to share?

@ShwetKhatri2001 i would like to add shreya ghosal to list of best artist as you have asked me. so plz assign it to me under swoc'24. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead.
