### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by Sanjana787** [ShwetKhatri2001/Swetify-Music#120]
### Description

The form for user information accepts numeric values as well. It should just accept the character values only.

### Screenshots

![3](https://github.com/ShwetKhatri2001/Swetify-Music/assets/141259407/df24f5c4-8b8b-45cd-8a53-1a076459ae41)
![4](https://github.com/ShwetKhatri2001/Swetify-Music/assets/141259407/0b61e1d3-653c-441a-a9f6-be0958a427cd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by Sanjana787** [comment]
@ShwetKhatri2001  please assign this issue to me.

**Comment by ShwetKhatri2001** [comment]
Okay, you can fix this.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Sanjana787 ? Please try to complete it in the next 3 days.

**Comment by Sanjana787** [comment]
ok @ShwetKhatri2001
