### ISSUE TITLE
Redesign the navbar and the toggle icon

### ISSUE THREAD

**Issue by Aadhya-Sharma** [ShwetKhatri2001/Swetify-Music#126]
### What's the style idea?

We need to improve the navbar as it is not visually appealing enough and replace the current toggle button with a more effective toggle button.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
@Aadhya-Sharma We are going to have a rich sidebar soon. I don't see much to do on the Navbar after that. I'd like to know what kind of changes you'd like to make on the existing navbar.

**Comment by Aadhya-Sharma** [comment]
@ShwetKhatri2001 The current toggle icon needs to be replaced with a more enhanced one, and I wanted to add the glassmorphism effect to the navbar. You may, however, close this issue because you indicated that there won't be a need for it after the side bar is implemented.

**Comment by ShwetKhatri2001** [comment]
Closing it because it's fixed already.
