### ISSUE TITLE
[BUG] <FORM VALIDATION ISSUE IN CONTACT>

### ISSUE THREAD

**Issue by mansi1309** [ShwetKhatri2001/Swetify-Music#128]
### Description

When we are entering numeric values in place of Names in contact section in the form then it is accepting and after clicking on send ..it is submitting the form ,So I would like to solve this issue by showing alert message on the screen that enter characters only when entering numeric numbers.

### Screenshots

https://github.com/ShwetKhatri2001/Swetify-Music/assets/133951716/85c4a16a-0a62-4db6-a018-03716993cb2f

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by mansi1309** [comment]
@ShwetKhatri2001 Please assign this issue to me

**Comment by ShwetKhatri2001** [comment]
It's a duplicate issue. Have a look at Issue #120 .

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it's a duplicate.
