### ISSUE TITLE
Smooth scroll and designing

### ISSUE THREAD

**Issue by TeekshaHarish** [ShwetKhatri2001/Swetify-Music#13]
When we click on a link in navbar like Categories it abruptly goes to that section. I wish to add smooth scrolling feature in this.

Also the song card should have some margin in top and bottom as it just sticks to the navbar and the footer.
![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/102624456/9180cf23-49c7-4399-8b6d-253355277153)

Adding a favicon

**Comment by ShwetKhatri2001** [comment]
Go ahead @TeekshaHarish and add your changes.
