### ISSUE TITLE
style: change to song pages

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [ShwetKhatri2001/Swetify-Music#132]
### What's the style idea?

We need to improve the design of the music div. 
the right section of the music div should be bottom of the music div.
and I want to small width and height of music div.

<img width="364" alt="image" src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/69814563/fcce2ffe-82d2-4b60-9026-c5716426f691">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
This page is going to be replaced completely soon. So, no need to work on it.

**Comment by ShwetKhatri2001** [comment]
The page has been redesigned, but the issues on the player are still there. 
Let me know if you're interested in working on it.

**Comment by ShwetKhatri2001** [comment]
`Top Hollywood Hits` and `Best Of Arijit Singh` playlist pages need improvement.

**Comment by BamaCharanChhandogi** [comment]
@ShwetKhatri2001 you can check
