### ISSUE TITLE
[Feature] - Playlist of Liked Songs / Favourites

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/Swetify-Music#16]
There will be a heart kind of button with two variations ( empty and filled ). Onclick on it the variation will toggle and if it's filled, it means the user has liked that song and it will be added to the "Your Favourites" playlist. We can have a card inside "Top Picks For You" as "Your Favourites" which will basically play the liked songs as a playlist just like other lists we have.

**Comment by Sami3160** [comment]
i am interested to handle this issue, please tell me difficulty, and is it for program code peak 2023?
please assign this issue to me😀

**Comment by Albert-2** [comment]
Hey @ShwetKhatri2001, i would really like to contribute to this feature
can you please assign me the same under codepeak'23
THANK YOU FOR CONSIDERING.... :)

**Comment by ShwetKhatri2001** [comment]
As the first commenter @Sami3160 I'm assigning you to work on this first. The deadline will be 4 days.
It's a medium-level issue as I see the minimum requirements, but the final label will depend on the quality of work done.

**Comment by Sami3160** [comment]
> As the first commenter @Sami3160 I'm assigning you to work on this first. The deadline will be 4 days.
> It's a medium-level issue as I see the minimum requirements, but the final label will depend on the quality of work done.

Sounds more than medium but fine ill be doing it😃
