### ISSUE TITLE
Having a Seprate Contribution.md 

### ISSUE THREAD

**Issue by Devesh-Daku** [ShwetKhatri2001/Swetify-Music#17]
I'd like to suggest for having a better contribution.md file will be good 
as this project is a opensource 
having a better contribution.md will be helpful for new contributors

**Comment by ShwetKhatri2001** [comment]
Sure, you can add it having details related to this project.

**Comment by ShwetKhatri2001** [comment]
Any updates @Devesh-Daku ? Please try to make your changes and create a PR in the next 3 days.

**Comment by Devesh-Daku** [comment]
Sorry, I forgot to give updates , I am travelling, tomorrow night ill reach home. If you're in hurry you can assign to anybody else, ihad started working on it but , due to some reason I have to travel, so I'll continue only after 14 dec

**Comment by Devesh-Daku** [comment]
If you can wait for 14th evening, i can send pr by 14th evening

**Comment by ShwetKhatri2001** [comment]
Sure, No worries.
