### ISSUE TITLE
Feat: Changing The Background Color of the website.

### ISSUE THREAD

**Issue by Mayank77maruti** [ShwetKhatri2001/Swetify-Music#18]
The background color of the websote can be changed so that website looks more visually appealing.
Below I am attaching the SS of how the website would look....
![Screenshot 2023-12-08 110902](https://github.com/ShwetKhatri2001/Swetify-Music/assets/125661248/b26d9254-b182-435d-ada9-77c68e3aa13d)
![Screenshot 2023-12-08 110930](https://github.com/ShwetKhatri2001/Swetify-Music/assets/125661248/451c21be-f868-4410-8d55-8ecb9bfdafb6)

**Comment by Mayank77maruti** [comment]
Hey @ShwetKhatri2001 , please do assign this task to me under codepeak'23 tag , I am eager to work on this task.

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead @Mayank77maruti. Also, I'd recommend to have blue as the primary color and have some more colors near to it.

**Comment by Mayank77maruti** [comment]
color 1:
![color1](https://github.com/ShwetKhatri2001/Swetify-Music/assets/125661248/97d9f00e-695d-47f9-8f4b-2253b4f15523)
color 2:
![color2](https://github.com/ShwetKhatri2001/Swetify-Music/assets/125661248/2b6de1e1-0ab6-4a58-81d6-e626ad007de2)
color 3:

https://github.com/ShwetKhatri2001/Swetify-Music/assets/125661248/d1f6ee28-56c1-4b92-98af-16eea50c2e9f

If I need to change the colors more please do let me know.
