### ISSUE TITLE
Bug: Font style issues

### ISSUE THREAD

**Issue by Molik2801** [ShwetKhatri2001/Swetify-Music#19]
there are 2 issue i like to address.

1. Blue font color is not going well with black background color.
2. And  i guess italics is not a good idea for home , popular categories and best of artists . it must be bold and light in color .

![Screenshot 2023-12-09 195415](https://github.com/ShwetKhatri2001/Swetify-Music/assets/116110308/d3084caf-c4e9-4fbb-b1e5-82c86f43d1f5)

**Comment by Molik2801** [comment]
i would like to fix these issues under codepeak

**Comment by ShwetKhatri2001** [comment]
I agree with your suggestions @Molik2801 ! Go ahead and make your proposed changes.
