### ISSUE TITLE
Feat: Adding a Loop Button Feature.

### ISSUE THREAD

**Issue by Mayank77maruti** [ShwetKhatri2001/Swetify-Music#22]
If  a user wants to listen to the song over a loop he can click on the loop button.

**Comment by Mayank77maruti** [comment]
Hey @ShwetKhatri2001 , please do assign this task to me under the tag of codepeak'23.

**Comment by ShwetKhatri2001** [comment]
Okay ! Looks like a good feature the application should have. Go ahead and add it.

**Comment by Mayank77maruti** [comment]
Hey @ShwetKhatri2001 , I have not been able to do it properly so unassign me this task.
