### ISSUE TITLE
[Feature]: Add spotify API to enhance user experience

### ISSUE THREAD

**Issue by Yash-Ainapure** [ShwetKhatri2001/Swetify-Music#26]
By adding spotify API , users can authorize their spotify account here and this can add multiple features to this website.
such as: listing users top songs listened ,top artists ,etc with the help of the API

Would love to contribute here,
Thanks.

**Comment by Yash-Ainapure** [comment]
Please assign me this issue so that i could start the work.

**Comment by Yash-Ainapure** [comment]
> Great idea, I thought of it some days ago and was looking for someone who'd like to contribute. 
> You can start working on this.
> 
> Let me know if you can implement these things for this issue to be considered as 'hard'.
> 
> Create a section 'Your Spotify music' and add a button to 'Log in with Spotify'  first.
> If authenticated then change that to 'Choose another account' to login using different account.
> If authenticated then show a card 'Your Top Songs' on click to which the songs should start playing as a playlist similar to the category playlists we have.

Great idea 👍😄

**Comment by Yash-Ainapure** [comment]
heyy @ShwetKhatri2001 ,I have done half of the work,I need some more time atleast 1-2 days.
will raise a pr till tommorrow afternoon.

**Comment by Yash-Ainapure** [comment]
@ShwetKhatri2001 

https://github.com/ShwetKhatri2001/Swetify-Music/assets/136250383/b55812b1-1bfc-4829-b342-33224b7f1743

what do you think about this or do i have to make other changes to it?
we cannot play the songs through api, we can just show users data such as most listened,favourite,etc
I will style to it at last

**Comment by ShwetKhatri2001** [comment]
Yes, it's looking fine. You can start working on how to show this data. 
You may use cards like structure for each song and show two scrollable lists having data fetched after successful login.
