### ISSUE TITLE
style: Fix Navbar alignment, distorted images, favorite track list

### ISSUE THREAD

**Issue by SamIsTheFBI** [ShwetKhatri2001/Swetify-Music#30]
## :question: Problem Description

- Navbar alignment is messed up
- Artist images are distorted in the landing page
- Favorite tracks list shows up below the footer

## :camera: Screenshots

<div align="center">

|![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/70562711/d6ebfd55-a6dd-4b40-8561-970d839fbffc) |
|--|
| <div align="center"> **Distorted Images (Look at Ritviz picture)** </div>|

|![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/70562711/51aae901-f510-496d-9185-7f2fe7612d34)|
|--|
| <div align="center"> **Hamburger icon isn't aligned properly** </div>|

|![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/70562711/3929a99c-5a89-4edb-8af7-1c6ce33e1546)|
|--|
| <div align="center"> **Navbar elements not aligned properly with the logo** </div>|

|![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/70562711/18539534-38a1-413e-98a0-f840f6f21a52)|
|--|
| <div align="center"> **Favorite tracks list shows up below footer** </div>|

</div>

## :framed_picture: Proposed Solution

- I wish to solve the above mentioned problems.

## :page_with_curl: Are you contributing for a program?

- I wish to contribute towards fixing this issue under <kbd>CodePeak '23</kbd>

**Please consider assigning me this issue.**

**Comment by ShwetKhatri2001** [comment]
Good findings. You can start fixing them all.

**Comment by Albert-2** [comment]
hey @ShwetKhatri2001
Can you please assign me this issue if no one is still working on it
THANK YOU....!!!:)
