### ISSUE TITLE
Front end issues

### ISSUE THREAD

**Issue by Souvik34** [ShwetKhatri2001/Swetify-Music#34]
There are certain responsive issues in this website. More over the colour gradients are mix matching. 
I would be happy to contribute to this project and will make some severe changes like the nav bar, add some cool transitions and do the above ones too.

**Comment by ashajyothi06** [comment]
@ShwetKhatri2001 can you assign me this?

**Comment by Souvik34** [comment]
@ashajyothi06  I have already worked on it

**Comment by ShwetKhatri2001** [comment]
Okay, @Souvik34 You're assigned. Just make sure you don't keep working on the issues raised and assigned previously.

**Comment by ShwetKhatri2001** [comment]
The Navbar looks fixed with the latest merge. Pull and have a look at the latest changes if you're working on it.

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it's already solved.
