### ISSUE TITLE
Adding a song list in playlist

### ISSUE THREAD

**Issue by drockparashar** [ShwetKhatri2001/Swetify-Music#37]
In the current application, when a user clicks on a playlist like:- Top Hollywood Hits, the page automatically opens the music player, instead we can create a list of songs for each playlist and then move on to the music player after user chooses a song.

for example-
 
![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/118686637/aede6794-329d-4788-b41a-6b87a47b08ad)

**Comment by ShwetKhatri2001** [comment]
Good idea @drockparashar ! It will make the exploration of the songs better.

You can start working on it. Make sure you stick to the theme colors and font while developing UI.
