### ISSUE TITLE
Adding a sign in/up page

### ISSUE THREAD

**Issue by Abhishek-465** [ShwetKhatri2001/Swetify-Music#38]
Title: Adding a sign in/up page

The website does not have the login page. I want to add it with the help of HTML,CSS and Javascript.
Screenshot:
![Screenshot (31)](https://github.com/ShwetKhatri2001/Swetify-Music/assets/127030695/e5e15255-b776-46b2-9515-073e29e32499)

Kindly assign me this issue.
I am contributing under KWOC.

**Comment by ShwetKhatri2001** [comment]
@Abhishek-465 I don't think we need it at this time since the platform is open for all and we are not saving much of user specific data. But thanks for raising this.

**Comment by Abhishek-465** [comment]
Okay then. Thank you
