### ISSUE TITLE
add an about section for the website

### ISSUE THREAD

**Issue by GAGANRAGHAV** [ShwetKhatri2001/Swetify-Music#43]
adding about section can boost the reach of the repository ....and tell fetures , playlist and functionality of website

**Comment by ShwetKhatri2001** [comment]
Sure, you can add that section above Footer. For content, you can refer to our README.

**Comment by ShwetKhatri2001** [comment]
Any issues or updates @GAGANRAGHAV ? Today is the last day of `Codepeak23`.

**Comment by GAGANRAGHAV** [comment]
@ShwetKhatri2001 added the about section ...please merge the pr

**Comment by ShwetKhatri2001** [comment]
Hey ! Can you just make it non-italic and add some space between lines. It's a bit hard to read.

**Comment by Shreyansh-333** [comment]
I can work on the About Us page if it still needs to be done. Please let me know.

**Comment by GAGANRAGHAV** [comment]
@ShwetKhatri2001  done sir 👍
