### ISSUE TITLE
Updates on CSS of website

### ISSUE THREAD

**Issue by rakesh-vajrapu** [ShwetKhatri2001/Swetify-Music#46]
Want to make some updates on CSS of the website. Please assign this issue to me @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Please specify what kind of changes you're proposing.

**Comment by rakesh-vajrapu** [comment]
> Please specify what kind of changes you're proposing.

I have made a PR

**Comment by ShwetKhatri2001** [comment]
Okay, You're assigned.
