### ISSUE TITLE
Adding scroll-reveal to improve the UI || Work under KWoC

### ISSUE THREAD

**Issue by sambitsingha** [ShwetKhatri2001/Swetify-Music#49]
**The scroll reveal , if added will load the elements one affter the other. It can be customised according to time-delay and directions according the UI.**

 **I would like to work on it for KWoC 2023 :)**

**Comment by ShwetKhatri2001** [comment]
Looks interesting. Go ahead and implement it for most of the elements present on website.

**Comment by sambitsingha** [comment]
### Yes I can do this , **but I wanted to let you know this.**

![Screenshot (107)](https://github.com/ShwetKhatri2001/Swetify-Music/assets/110420002/e9e2ed6a-80ee-4a06-939b-49cd817c9e75)

 As you can see , **this section is missing a lot of elements ( texts , links , images , etc )**. If more elements are added , the effect would be more prominently visible. But as told , I will add the effect to as much as classes possible currently.

**Comment by ShwetKhatri2001** [comment]
The sections should not be completely hidden since it will hide the features of our application. They should come with an effect when scrolled to their level. May be try for some elements first where you're not facing such challenges.

**Comment by sambitsingha** [comment]
@ShwetKhatri2001  I have added a PR #50 for this.

**Comment by sambitsingha** [comment]
@ShwetKhatri2001  Can you add me in the README.md contributor list
