### ISSUE TITLE
Add a Get In Touch/Contact Us page

### ISSUE THREAD

**Issue by PSS2134** [ShwetKhatri2001/Swetify-Music#53]
@ShwetKhatri2001

**Comment by ayann07** [comment]
I want to work on this under KWOC

**Comment by ShwetKhatri2001** [comment]
Okay assigning you @PSS2134 since you raised it. 
Add the `Get in Touch` section above Footer and make sure you use our theme colors and font matching with other sections.

**Comment by PSS2134** [comment]
@ShwetKhatri2001  I have created the PR #54 .

**Comment by PSS2134** [comment]
@ShwetKhatri2001 Check this as well

**Comment by PSS2134** [comment]
@ShwetKhatri2001 Could you check?
