### ISSUE TITLE
[ Bug ] - Make all controls present in song-player working

### ISSUE THREAD

**Issue by ShwetKhatri2001** [ShwetKhatri2001/Swetify-Music#57]
There are few buttons present in the song-player as follows,
- Play next song,
- Play previous song
- Shuffle songs
- Loop song
- Add song to favourites
- Download song
- Show song prorgress
- Skip back in song by 10 seconds

The functions / event listeners for all these actions are already present in `swetify.js` , just need to make them work again with our Redesigned UI present currently.

**Comment by sonidhruv26** [comment]
Hey Shwet, I can solve this, kindly assign me.

**Comment by JrG-One** [comment]
Kindly assign me 
i think i can solve thsi issue

**Comment by ShwetKhatri2001** [comment]
Okay, @sonidhruv26 as a first commenter I'm assigning it to you. 
Try to solve it within the next 3 days.
