### ISSUE TITLE
Shuffle Play Button 

### ISSUE THREAD

**Issue by Mrudula1205** [ShwetKhatri2001/Swetify-Music#6]
I would like to add a shuffle play button in music controls.
Please assign me this issue under hacktoberfest tag

**Comment by ShwetKhatri2001** [comment]
Go ahead @Mrudula1205. Make sure you've registered for Hacktoberfest and getting your PRs listed there.

**Comment by Mrudula1205** [comment]
Yes, my PRs are getting listed in Hacktoberfest profile
