### ISSUE TITLE
Recommendation:

### ISSUE THREAD

**Issue by maadi7** [ShwetKhatri2001/Swetify-Music#64]
hii @ShwetKhatri2001, aditya here. it is a great project. I have a few recommendations for this project like we can connect to mongodb allowing authentication and making playlist for users and many other functionalities. just if you think of expanding it I would like to help you with it. I am a contributor under SWOC.

**Comment by ShwetKhatri2001** [comment]
There are lot of things if we think of having a backend like creating a server, saving all songs data to a database, set up authentication and save user's data. Let me know what would you like to start first and what ideas you have of implementing a backend for this.

**Comment by ShwetKhatri2001** [comment]
Closing it because of inactivity.
