### ISSUE TITLE
Music Player UI upgradation.

### ISSUE THREAD

**Issue by Ayush-sss** [ShwetKhatri2001/Swetify-Music#68]
The UI of music player is bit dull compared to the popular music apps like spotify and amazon music . It should be more attractive as it is the most important component the user notice while listening to music. Please let me work on this issue @ShwetKhatri2001 
![Screenshot 2023-12-29 143324](https://github.com/ShwetKhatri2001/Swetify-Music/assets/106423359/4f610b57-3472-4d65-ad6e-84eee3a31f61)
We need to make it more cool

**Comment by ShwetKhatri2001** [comment]
Okay, you can work on it. Also, have a look at the player we have on other playlists since that's the latest one.

<img src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/56475750/cd5e8b5e-ab72-4c56-b745-73b67e3a1ccc" width="400" />

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Ayush-sss ? 
Few more contributors are also interested in working on this. 
Please try to complete the changes you want to make within the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Let's give a chance to other contributors to work on this. This issue is open to contributors.

**Comment by ShwetKhatri2001** [comment]
Closing this issue because it's a duplicate and inactive.
