### ISSUE TITLE
Update the Artist Playlists (Arijit Singh)

### ISSUE THREAD

**Issue by divyeshpillai7** [ShwetKhatri2001/Swetify-Music#69]
I would like to work and update the artists playlists, When we click on any artist, it just directly starts playing a song. Instead it would be better if it first displays the list of songs by the artist and then allow the user to select one and play it. I would first start with the arijit singh playlist.
Please assign me this issue.
I'm working on this under SWOC 24
<img width="1066" alt="Screenshot 2024-01-01 at 2 14 17 PM" src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/123104654/db30e5b2-e43b-4226-97ae-aa9e40e70512">

something like this

**Comment by ShwetKhatri2001** [comment]
Go ahead @divyeshpillai7 ! 
We also have some related work done in past as you can see in PR https://github.com/ShwetKhatri2001/Swetify-Music/pull/60 and experience it live by opening `Top Hollywood Hits`. I have mentioned few improvements on that implementation in Issue #61 . Try to create a playlist page with all those things covered. Your deadline is 5 days considering it a `Medium` level issue for now. You may get the next level points based on the quality of contribution.

**Comment by divyeshpillai7** [comment]
Sure! Thanks for assigning me this issue.
I'll try my best n complete it within the deadline.

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001  I am done with the designing of the UI for the playlist, but I am stuck in the javascript part of it.
I'm yet to link the songs with their respective tabs.
Here's how it looks
Please give me some more time so that i can figure out stuff and finish it completely.

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001  I am done with the designing of the UI for the playlist, but I am stuck in the javascript part of it.
I'm yet to link the songs with their respective tabs.
Here's how it looks
Please give me some more time so that i can figure out stuff and finish it completely.
![Uploading Screenshot 2024-01-06 at 2.43.14 PM.png…]()

**Comment by divyeshpillai7** [comment]
@ShwetKhatri2001 I am done with the designing of the UI for the playlist, but I am stuck in the javascript part of it.
I'm yet to link the songs with their respective tabs.
Here's how it looks
Please give me some more time so that i can figure out stuff and finish it completely.
<img width="1440" alt="Screenshot 2024-01-06 at 2 43 14 PM" src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/123104654/7ee436dc-344a-405e-bf3b-b99926187f52">

**Comment by ShwetKhatri2001** [comment]
Sure, take your time. It's looking great! 
Also, we have modified our JS code and functions. It should be easy for you to integrate the songs playlist now.

**Comment by divyeshpillai7** [comment]
Thank you! Sure I'll do it

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @divyeshpillai7 ? Please try to complete this in the next 3 days.

**Comment by divyeshpillai7** [comment]
Yes @ShwetKhatri2001 , I'm still working on it..., it's taking some time for me as I'm learning and then implementing..sry for that.I'll complete it within the time, thanks for being so patient :)

**Comment by ShwetKhatri2001** [comment]
@divyeshpillai7 Will you be able to complete it in the next few days?

**Comment by divyeshpillai7** [comment]
> @divyeshpillai7 Will you be able to complete it in the next few days?

Yes @ShwetKhatri2001 I'm done doing it.
I have modified the playlist page for arijit singh as well as the hollywood songs playlist

**Comment by divyeshpillai7** [comment]
if permitted i can do the same for the other playlist as well ! :) @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Completed in PR #135
