### ISSUE TITLE
Remove repetition of Code || Adding Json files

### ISSUE THREAD

**Issue by AMBIRASHAH-PRAJAPATI** [ShwetKhatri2001/Swetify-Music#70]
1) their are so much js code is repeated in the files- contact, index and about.
2) in the js file we directly used variables and encoded json their in js files we can use separate json file, if not want to use database

**Comment by ShwetKhatri2001** [comment]
Good idea, Want to work on this? Any open-source program you're taking part in?

**Comment by AMBIRASHAH-PRAJAPATI** [comment]
yah, i want to work on this, i am mentor at swoc 24,
but found some of upgradation in the code and want to do that.

**Comment by ShwetKhatri2001** [comment]
Okay, make sure you don't break any functionality or UI while making your changes.
