### ISSUE TITLE
Add dark  mode and light mode toggle 

### ISSUE THREAD

**Issue by raghav1482** [ShwetKhatri2001/Swetify-Music#71]
Add dark  mode and light mode toggle  using Javascript

KINDLY ASSIGN ME THIS ISSUE UNDER #SWOC24  @ShwetKhatri2001

**Comment by ShwetKhatri2001** [comment]
Okay @raghav1482 , You may add a toggle button in Navbar and have a list of colors for both themes to be changed. 
The current version will work for Dark mode.

**Comment by raghav1482** [comment]
Sure , i will proceed

**Comment by raghav1482** [comment]
Kindly add label  SWOCS4 to the issue @ShwetKhatri2001

**Comment by bhavya-anand19** [comment]
@ShwetKhatri2001 I would like to work on this issue.

**Comment by raghav1482** [comment]
Completed by tomorrow

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @raghav1482 ?

**Comment by ShwetKhatri2001** [comment]
Please try to complete this in the next 3 days.

**Comment by raghav1482** [comment]
> Please try to complete this in the next 3 days.

I have completed it. Would be creating PR soon
