### ISSUE TITLE
Template for Issue Creation

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [ShwetKhatri2001/Swetify-Music#73]
- Templates for issue creation
- Categories them into either bug, feature, enhancement, etc.
- Easy to understandable.
- Best experience for the user while creating the issue.
- Enough information, they can give or explain about the issue.

**Comment by Avdhesh-Varshney** [comment]
@ShwetKhatri2001 please assign it to me to contribute under SWOC'24

**Comment by ShwetKhatri2001** [comment]
Sure, You can work on that.
