### ISSUE TITLE
Implementing a scrolling sidebar with a toggle effect, similar to YouTube's interface.

### ISSUE THREAD

**Issue by Navya-1212** [ShwetKhatri2001/Swetify-Music#75]
- *Objective*: My goal is to create a webpage feature that mirrors the interface of YouTube, with a specific focus on developing a sidebar equipped with both scrolling and toggling functionalities.

- *Scrolling Sidebar*: I aim to design a sidebar that can be scrolled, indicating its capacity to handle a list of items that might extend beyond the visible area. This feature is reminiscent of YouTube's sidebar, where various navigation options are conveniently accessible.

- *Toggle Effect*: Additionally, I want the sidebar to feature a toggle effect, enabling users to expand or collapse it with a designated action, like clicking a button or an icon. This functionality mirrors what is commonly observed on YouTube, allowing the sidebar to be hidden for a more expansive view of the main content.

- *User Interaction*: The toggle effect should respond to user interactions, ensuring that the visibility of the sidebar can be controlled based on user preferences or the need for a more streamlined content view.

- *Visual Resemblance to YouTube*: Throughout the implementation, I'll strive to ensure a visual resemblance to YouTube's interface. This includes incorporating similar color schemes, styling, and an overall design that provides users with a familiar and user-friendly experience.

**Comment by ShwetKhatri2001** [comment]
Looks like a good idea. You can start working on this. Make sure you use the theme colors, font and develop it responsively for all viewports. I'm assigning `Medium` level to this issue for now. The final level will depend on the quality of contribution.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Navya-1212 ?

**Comment by Navya-1212** [comment]
Yes I am working on sidebar

**Comment by ShwetKhatri2001** [comment]
Please try to complete this in the next 3 days.

**Comment by Navya-1212** [comment]
I am working on it

**Comment by ShwetKhatri2001** [comment]
Let's give a chance to others work on this. This issue is open to contributors.

**Comment by Navya-1212** [comment]
I have completed most of the part, I just customising for different screens

**Comment by Navya-1212** [comment]
I have completed most of the part, I just
 customising for different screens

**Comment by Navya-1212** [comment]
![IMG-20240124-WA0085](https://github.com/ShwetKhatri2001/Swetify-Music/assets/153123905/bd3a8bb5-95fc-4625-a3c9-ef9caa2751c6)
![IMG-20240124-WA0084](https://github.com/ShwetKhatri2001/Swetify-Music/assets/153123905/1deed6a3-c9bf-451c-baac-23fe04de0fcf)

**Comment by ShwetKhatri2001** [comment]
Sure, I will accept your contribution, but I need to keep it open if someone else also wants to contribute.
