### ISSUE TITLE
contact page

### ISSUE THREAD

**Issue by Niharika0104** [ShwetKhatri2001/Swetify-Music#76]
**ui improvement for contact page**.
I would also like to do overall ui improvements in the website.
<img width="943" alt="snap3" src="https://github.com/ShwetKhatri2001/Swetify-Music/assets/124892559/8bfc78fa-5c44-43ca-8f91-cc702bfe862d">

**Comment by Niharika0104** [comment]
please assign this issue to me

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead. Make sure you follow the theme colours & font and don't break anything .

**Comment by anamithrak15** [comment]
@ShwetKhatri2001 I would like to contribute on this issue. Please assign this to me under swoc'24.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @Niharika0104 ? Please try to complete this in the next 3 days.

**Comment by Niharika0104** [comment]
Okay sure

**Comment by ShwetKhatri2001** [comment]
Completed by PR #123
