### ISSUE TITLE
hover issue on top hollywood hits

### ISSUE THREAD

**Issue by RehanChalana** [ShwetKhatri2001/Swetify-Music#78]
https://github.com/ShwetKhatri2001/Swetify-Music/assets/139042983/8e4404e4-0c63-4b79-88da-2a4f08757989

Cursor is changing to pointer instead of text cursor
and text is getting red underline

Please Share your thoughts on this and tell me if i can start working on it

**Comment by ShwetKhatri2001** [comment]
Okay, you can fix this.
