### ISSUE TITLE
Adding Favicon Icon

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [ShwetKhatri2001/Swetify-Music#79]
I would Like To Add a Favicon Icon To The Webpage According To the Theme Of The Webpage.

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Assign This Issue To Me Under SWOC

**Comment by ShwetKhatri2001** [comment]
Okay, come up with something matching with theme colors and font.

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Check Sir... ?
