### ISSUE TITLE
Expand Side Bar In The Music App

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [ShwetKhatri2001/Swetify-Music#80]
I would Like To Expand the Side Nav Bar In The Web Page

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Assign This Issue To Me Under SWOC

**Comment by ShwetKhatri2001** [comment]
Didn't get you exactly. Can you elaborate.

**Comment by Kapileswar-Moharana** [comment]
@ShwetKhatri2001 Ok Suppose There is A Nav Bar In the Desktop View And the Mobile View It is ConVerted Into a Left Side Bar 3-Bar On Clicking Over It Expand Its Feature Like Now on Your Website.

**Comment by ShwetKhatri2001** [comment]
Okay, but it will be covered in one of the issues raised already. Have a look at Issue #75 .

**Comment by ShwetKhatri2001** [comment]
Closing this because it's a duplicate issue.
