### ISSUE TITLE
Suggestions for improving website UI/UX

### ISSUE THREAD

**Issue by cjstyles6** [ShwetKhatri2001/Swetify-Music#82]
While testing the site, I noticed some opportunities to improve the overall user interface and experience,I'm happy to put together some mockups and/or a PR to demonstrate potential UI updates for review

**Comment by ShwetKhatri2001** [comment]
We have redesigned it recently. If you have better mockup ideas and I'd like to know about that first.

**Comment by cjstyles6** [comment]
sure

**Comment by ShwetKhatri2001** [comment]
Closing it because of inactivity.
