### ISSUE TITLE
Improve design of Popular Categories

### ISSUE THREAD

**Issue by tarnibalgoher5** [ShwetKhatri2001/Swetify-Music#88]
The design of the play song page under popular categories can be made better. I also noticed it is not responsive.

**Comment by ShwetKhatri2001** [comment]
Tell me what kind of changes you'd like to make. Also, have a look at some related issues first such as Issue #68

**Comment by tarnibalgoher5** [comment]
Okay, i will check the previous issue first.

**Comment by tarnibalgoher5** [comment]
The changes I would suggest are:

- Since there is blank space, we can show either a **list of other songs** from the artist or **Recently played**
- At the bottom we can display the song playing.

**Comment by ShwetKhatri2001** [comment]
Confirm, Which blank space you are talking about. 

Recently played Songs list looks interesting and can be done if you're interested in it.

We can save the list of songs in local storage similar to the `Liked Songs` being displayed at the bottom. Every song which will be played for at least half its duration will get added to the `Recently Played Songs` list's front as the first song in the list. Also, keep only the latest 10 songs at max in the list. 

Let me know if you'd like to implement it.

**Comment by tarnibalgoher5** [comment]
Yes sounds to me too. 
I'll attach a screenshot for the blank space in the morning.

**Comment by tarnibalgoher5** [comment]
![Screenshot 2024-01-05 155839](https://github.com/ShwetKhatri2001/Swetify-Music/assets/92452739/be97e216-663c-4e20-9222-01139984ab3a)
This is what I was referring to

**Comment by tarnibalgoher5** [comment]
@ShwetKhatri2001 should I start working on this?

**Comment by ShwetKhatri2001** [comment]
We are going to have a playlist page having all songs of a category listed and the song playing is also already being shown in your screenshot. What exactly you want to work on then?

**Comment by tarnibalgoher5** [comment]
work on the design of the above page, this looks good but we can make it better

**Comment by ShwetKhatri2001** [comment]
Okay, you can improve it and make it more creative.
