### ISSUE TITLE
Enhance: Adding a Favicon to the site!!

### ISSUE THREAD

**Issue by DeepRahangdale** [ShwetKhatri2001/Swetify-Music#9]
Tell me what's else you need !!
would love to contribute.

**Comment by saurabhgdeshmukh** [comment]
assign this task to me and please elaborate on the issue

**Comment by Molik2801** [comment]
@ShwetKhatri2001 i would like to contribute to it

**Comment by ShwetKhatri2001** [comment]
Hey Guys ! Thanks for reaching here, but I think the favicon is good to go for now. 
There are some more features this application can have and I'm looking for contributors for those.
You're welcome to create issues for the features coming out of your creativity.

**Comment by ShwetKhatri2001** [comment]
Closing this because it's already fixed.
