### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by GhoshAditi** [ShwetKhatri2001/Swetify-Music#90]
![image](https://github.com/ShwetKhatri2001/Swetify-Music/assets/144611267/0b8523c1-8158-4ba3-b531-ae91fc5cd439)

Here the spelling of Popular is incorrect. This actually creates a negative impression on the user. So i would like to fix this bug.
Please assign it to me under SWOC'24.

**Comment by ShwetKhatri2001** [comment]
Sure, this should be fixed. You can fix that.
