### ISSUE TITLE
Making contact page responsive.

### ISSUE THREAD

**Issue by maadi7** [ShwetKhatri2001/Swetify-Music#93]
hii @ShwetKhatri2001, please assign me this.

**Comment by ArshiyaArora** [comment]
@ShwetKhatri2001  can you please assign me this under SWoC

**Comment by ShwetKhatri2001** [comment]
Okay, @maadi7 you can start working on this.

**Comment by ShwetKhatri2001** [comment]
@maadi7 Please try to complete the changes you want to make in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Closing because the issue has been resolved already.
