### ISSUE TITLE
Music file size compression by reducing bitrate without losing quality by tuning as per requirement

### ISSUE THREAD

**Issue by JoydeepMallick** [ShwetKhatri2001/Swetify-Music#95]
### What would you like to share?

> Any easy to implement solution you have in mind for that ? Compressing audio files may work as well. The motive is to reduce the size of the project without disturbing the functionality.

@ShwetKhatri2001 I would like to compress the audio files so as to reduce the overall project size, on bit of research I find of reducing the `bit rate` can reduce size of files significantly but need to keep in mind not to reduce too much which will lead to loss of sound quality and a strange humming sound getting added.

Sample without compression (~5mb):- 

https://github.com/ShwetKhatri2001/Swetify-Music/assets/94801952/f3ecd409-d9c8-4181-a848-09d82be2879b

Sample with extreme compression(~1mb, 32kbps bit rate) -- sound gets a little strange melody reduced, this song seems to point out the fact more maybe due to some particular sound element(😅note : I am not into music)

https://github.com/ShwetKhatri2001/Swetify-Music/assets/94801952/0bcb34be-bbdf-4c0e-9b46-9eaf142e9b32

Sample with okok sound (~4mb, 128kbps bit rate) -- sounds decent to me

https://github.com/ShwetKhatri2001/Swetify-Music/assets/94801952/7ff7a56a-034c-4654-8282-c397322a2bd6

I would like to work on audio file size issue and compress them as much as possible without losing quality in `songs-images` folder under **SWOC 24** project contribution if you assign this issue to me. Hope my above idea will reduce the file size if not much but considerable amount.

Maybe at a later stage we can simply host all music in a remote server and then inside the `swetify.js` we can just add links to music and they will play, only keeping the images in folder in github would be enough then I guess.

 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShwetKhatri2001** [comment]
Okay, go ahead and compress the audio files.

**Comment by JoydeepMallick** [comment]
@

> Okay, go ahead and compress the audio files.

@ShwetKhatri2001 I am working on  it, sorry for the late reply. Well I am writing a python script which used ffmpeg to automate this process, I have some code which does this for single file but will make it to work on many files, please have a look on the demo file :-

This will need a `ffmpeg` to be installed on system to run and added to environment but doing this will reduce the hassle of compressing files manually and just run the script to do the same.

```
import os
import subprocess

# Specifying the paths to the original and compressed audio files
original_audio_path = "C:/Users/JOYDEEP/Desktop/SWOC/swetfy-music/music/001. Brishti Tomake Dilam.mp3"
compressed_audio_path = "Canon2.mp3"

# Construct the ffmpeg command with desired compression options
command = [
    "ffmpeg",
    "-i", original_audio_path,
    "-b:a", "108k",  # changed mind to 108kbps which also sounds ok but reduces file size more
    "-vbr", "3",  # this features seems to manipulate bitrate as per music 
    "-ac", "2",  
    compressed_audio_path
]

try:
    # Running the ffmpeg command using subprocess
    subprocess.run(command, check=True)
    print("Compression successful!")
except subprocess.CalledProcessError as e:
    print(f"Error: ffmpeg command failed with error code {e.returncode}")

```

Should I proceed further, what are your thoughts ?

### My plan 

To create a script to compress the audio files in the folder and overwrite them without doing manually.

Probably keep record or check files bitrate before compressing so that a compressed file is not over compressed.

**Comment by ShwetKhatri2001** [comment]
You can work on that script on your side and compress the files, but let's first only replace the current audio files with compressed files. You can push javascript code as part of the next issue which takes an audio file as input and export/download a compressed file. We will probably also have an interface to add songs on the platform, it will be useful at that time.

**Comment by JoydeepMallick** [comment]
@ShwetKhatri2001  I have raised a pull request regarding compression of audio files, would be helped if you review it at https://github.com/ShwetKhatri2001/Swetify-Music/pull/98

**Comment by JoydeepMallick** [comment]
> You can push javascript code as part of the next issue which takes an audio file as input and export/download a compressed file. We will probably also have an interface to add songs on the platform, it will be useful at that time.

Well so i need to convert my py file to javascript file and then integrate it with the input music feature once its added, 🤔 this sounds interesting and I need to figure it out how to do it, nice idea!
