### ISSUE TITLE
I have some ideas to make the website look even cooler and easier to use.

### ISSUE THREAD

**Issue by AjayAsnani** [ShwetKhatri2001/Swetify-Music#97]
### Description

Here's what I'm thinking:

1)-Fresh Look: Give it a more modern style, like using new fonts and arranging things in a cleaner way. 

2)-Clear Focus: Make the important parts stand out more, so people can find what they need quickly.

3)-Perfect Fit: Make sure it looks great on phones, tablets, and computers.

4)-Fun Touches: Add some little animations and surprises to make it more fun to use.

What do you think?
I'm open to all ideas, so let's chat about it!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/Swetify-Music/blob/master/CONTRIBUTION.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by ShwetKhatri2001** [comment]
Looks like you'll bring some good improvements to the platform. I'm assigning you to complete the tasks you've mentioned.

**Comment by ShwetKhatri2001** [comment]
Any updates or issues @AjayAsnani ? Please try to complete this in the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Closing it because of inactivity.
